### ISSUE TITLE
Error when filtering by platform

### ISSUE THREAD

**Issue by pmaciocia** [morosanmihail/HA-LondonTfL#4]
When I use a platform filter when adding a station I end up with no entity and this error in the logs.

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 737, in async_device_update
    await task
  File "/config/custom_components/london_tfl/sensor.py", line 160, in async_update
    self._tfl_data.populate(result, self.filter_platform)
  File "/config/custom_components/london_tfl/tfl_data.py", line 35, in populate
    self.filter_by_platform(filter_platform)
  File "/config/custom_components/london_tfl/tfl_data.py", line 54, in filter_by_platform
    self._raw_result = [
  File "/config/custom_components/london_tfl/tfl_data.py", line 56, in <listcomp>
    if item['platformName'] == self.filter_platform
AttributeError: 'TfLData' object has no attribute 'filter_platform'
```

I wasn't sure of the format to use for the platform filter so I tried a few variations of `Platform 2` and none of them worked.  Without the filter it works fine.

**Comment by morosanmihail** [comment]
Huh, that's not great. I'll try to replicate and fix next week. In the mean time, the mitigation is to use no filter. 
Thank you for the heads up!
